GET /api/v1/credentials/password?name=passTest HTTP/1.1
Host: credstore.cfapps.eu10.hana.ondemand.com
sapcp-credstore-namespace: com.roy.cred
authorization: Basic MWJiZDM4NDktODlmMS00YzA1LWJmNzMtYmMwZTg1MDMwMzQxLjAuUDhQNkd4Z1BiUVNsdVd1Q2NLYXRvUWR2a0FYKzB0eTNRaUUwcDZXRTJUdz06YXJDcldSeEF0Rk5EdHpLYVh2RHhqVEFQdE9XRTdHb2xHNE41amZLRDNPcG9MR1BPMzZOUlZHcUtickZzQ1cydy4wLnI0bHREZFVWS2lGZHpRVEkwbGxSZkZQOGQ2RS9yeHdxdUZURWN4anNOVzA9